export default {
    SET_LOGGED_USER: 'setLoggedUser',
    SET_MENU_AVATAR: 'setMenuAvatar',
    SET_TOKEN: 'setToken',
    SET_PRODUCT: 'setProduct',

    ADD_UPLOADED_FILE: 'ADD_UPLOADED_FILE',
    SET_UPLOAD_FILE_PROGRESS: 'SET_UPLOAD_FILE_PROGRESS',
    SET_UPLOAD_FILE_PROGRESS_ERROR: 'SET_UPLOAD_FILE_PROGRESS_ERROR',
    REMOVE_UPLOAD_FILE_PROGRESS: 'REMOVE_UPLOAD_FILE_PROGRESS',
    TOGGLE_ASIDE: 'TOGGLE_ASIDE',

    SET_NOTES: 'SET_NOTES',
    ADD_NOTE: 'ADD_NOTE',
}
